---

- hosts: all
  vars:

  tasks:
  - name: "Add user itesciadmin"
    become: true
    user:
            name: itesciadmin
  
  - name: "Deploying package apache2"
    become: true
    package:
            name: apache2
            state: present

  - name: "Deploying package bind9"
    become: true
    package:
            name: bind9
            state: present

  - name: "Deploying package htop"
    become: true
    package:
            name: htop
            state: present
            
  - name: "Deploying package vim"
    become: true
    package:
            name: vim
            state: present
            
            
            
            
            



